# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf43d3bdf13c362812af881d1f029994df69c5aaa7f8dee869e796c1fa76d5df9e2310b0b3562f9b89ec76f63a8149f9c6b6d51c3ac6503a3271c570ec40a1b3

test:
  secret_key_base: 6395a5e5d734a632aefe7f941f89400d4696861bfe4828e786aee25c9115c1f43a1779e95bf617d367fc6c7c602631d96d03156f1060a015921cd1e072ac54c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
